# Generated by Django 6.0.2 on 2026-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akoyiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
